import Link from 'next/link';
import { Shield, Lock, Eye, CheckCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function LandingPage() {
  return (
    <div className="max-w-5xl mx-auto px-4 py-16 space-y-20">
      {/* Hero */}
      <section className="text-center space-y-6">
        <div className="inline-flex items-center gap-2 text-xs font-mono text-[#0C447C] border border-[#0C447C]/30 px-3 py-1.5 rounded-full">
          <div className="w-1.5 h-1.5 bg-[#0C447C] rounded-full" />
          Powered by Dstack TEE · Shape Rotator Hackathon
        </div>
        <h1 className="text-5xl font-bold tracking-tight">
          Submit your pitch.<br />
          <span className="text-[#0C447C]">Judges never see it.</span>
        </h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Sealed Room runs AI evaluation inside a Trusted Execution Environment. Judges receive only the structured evaluation — your raw idea stays sealed with a cryptographic proof.
        </p>
        <div className="flex gap-4 justify-center">
          <Button asChild className="bg-[#0C447C] hover:bg-[#0C447C]/80">
            <Link href="/submit">Submit Your Pitch</Link>
          </Button>
          <Button asChild variant="outline">
            <Link href="/verify">Verify a Receipt</Link>
          </Button>
        </div>
      </section>

      {/* Three roles diagram */}
      <section className="space-y-8">
        <h2 className="text-2xl font-semibold text-center">How it works</h2>
        <div className="grid md:grid-cols-3 gap-6">
          <Card className="border-border/50 bg-card/50">
            <CardHeader>
              <Lock className="w-8 h-8 text-[#0C447C] mb-2" />
              <CardTitle>Team</CardTitle>
              <CardDescription>Submit your pitch</CardDescription>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-2">
              <p>Upload your pitch deck or description. It&apos;s encrypted before leaving your browser.</p>
              <p>Receive a hardware-signed attestation receipt proving it was processed inside the TEE.</p>
            </CardContent>
          </Card>
          <Card className="border-border/50 bg-card/50">
            <CardHeader>
              <Eye className="w-8 h-8 text-[#0C447C] mb-2" />
              <CardTitle>Judge</CardTitle>
              <CardDescription>See only the evaluation</CardDescription>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-2">
              <p>Receive an AI-generated 3-paragraph thematic summary with scores across 5 criteria.</p>
              <p>Ask follow-up questions — answered by AI inside the enclave, never exposing the raw submission.</p>
            </CardContent>
          </Card>
          <Card className="border-border/50 bg-card/50">
            <CardHeader>
              <CheckCircle className="w-8 h-8 text-[#0C447C] mb-2" />
              <CardTitle>Verifier</CardTitle>
              <CardDescription>Cryptographically verify</CardDescription>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground space-y-2">
              <p>Anyone can paste an attestation receipt and verify the TEE measurement and quote signature.</p>
              <p>Proves the evaluation was generated by the authentic enclave without human intervention.</p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Research basis */}
      <section className="border border-border/30 rounded-lg p-8 space-y-4 bg-card/20">
        <h3 className="font-semibold text-lg">Based on NDAI Agreements research</h3>
        <p className="text-muted-foreground text-sm leading-relaxed">
          Sealed Room implements the NDAI (Non-Disclosure AI) pattern from IC3 research by Andrew Miller and Flashbots.
          AI models inside TEEs can serve as trusted third parties — receiving confidential information, processing it,
          and returning structured outputs without ever revealing the raw input to any external party.
        </p>
      </section>
    </div>
  );
}
